# Introduction to PyTorch (25Spring)


References:
- PyTorch tutorials: https://pytorch.org/tutorials/
- PyTorch documentation: https://pytorch.org/docs/stable/index.html
- Prof. Matus Telgarsky's lecture: https://mediaspace.illinois.edu/channel/channelid/198647123

Please use try running code blocks yourself to better understand PyTorch.

**Announcement**: If you have a DRES letter, please send to Professor Gui ASAP.

In [2]:
import numpy as np
import torch

## Tensors
The core datatype in PyTorch. A tensor is a multi-dimensional matrix containing data elements of the same type.

In [ ]:
# Create tensors

# From lists
a = torch.tensor([0.1, 1.5, 2.3])
b = torch.tensor(range(4))
print(a, b)

tensor([0.1000, 1.5000, 2.3000]) tensor([0, 1, 2, 3])


In [ ]:
# From NumPy arrays
c = np.array([1, 2, 3])
print(c)
d = torch.from_numpy(c)
print(d)
d = torch.tensor(c) # same as from_numpy
print(d)

[1 2 3]
tensor([1, 2, 3])
tensor([1, 2, 3])


In [ ]:
# Can also go back to list/ndarray
print(b.tolist())
print(d.numpy())

[0, 1, 2, 3]
[1 2 3]


In [ ]:
# Create zeros and ones
zeros = torch.zeros(2, 4)   # 2 x 4 matrix
ones = torch.ones([2, 3, 4])  # 2 x 3 x 4 tensor
print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [ ]:
# Other fancier initialization functions
print(torch.empty(2, 4))            # Matrix with uninitialized values
print(torch.rand(5))                # Matrix with random numbers ~ uniform [0, 1]
print(torch.randn(5))               # Matrix with random numbers ~ normal(0, 1)
print()

print(torch.zeros_like(ones))       # Same shape as 'ones', but filled with all zeros
print(torch.empty_like(ones))
print(torch.rand_like(ones))
print(torch.randn_like(ones))
print()

print(torch.eye(3))                 # Identity matrix, I
print(torch.diag(torch.ones(3)))    # Diagonal matrix
print(torch.diag(torch.eye(3)))     # Diagonal elements in a matrix

tensor([[7.5816e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 6.4460e-44, 1.1578e+27, 1.1362e+30]])
tensor([0.2334, 0.8506, 0.7083, 0.7986, 0.9947])
tensor([-0.8330, -1.8490, -0.5517,  0.1681, -0.5514])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[7.1086e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
tensor([[[0.5466, 0.9612, 0.5893, 0.6353],
         [0.1035, 0.9073, 0.4320, 0.3440],
         [0.6086, 0.2543, 0.7598, 0.4925]],

        [[0.0332, 0.8773, 0.0888, 0.3472],
         [0.7913, 0.6865, 0.0475, 0.3225],
         [0.8090, 0.7892, 0.4435, 0.83

In [ ]:
# Opeartions on tensors
a = torch.FloatTensor(range(5))
print(a)
print(a * 2)
print(a ** 2)       # or print(a.pow(2))
print(a.exp())

tensor([0., 1., 2., 3., 4.])
tensor([0., 2., 4., 6., 8.])
tensor([ 0.,  1.,  4.,  9., 16.])
tensor([ 1.0000,  2.7183,  7.3891, 20.0855, 54.5981])


In [ ]:
# Matrix muliplication
b = torch.ones(3, 3)
print(b * b)    # Be careful, this is element-wise

print(b @ b)
print(b.matmul(b))

c = torch.ones(4)
print(c @ c)
print(c.dot(c))
print(c.matmul(c))

d = torch.randn(2, 3, 4, 5)     # (..., n, m), array of 2x3 matrices (size 4 x 5)
e = torch.randn(2, 3, 5, 6)     # (..., m, k), array of 2x3 matrices (size 5 x 6)
print((d @ e).shape)            # (..., n, k), matmul multiplies the last two dimensions as two matrices

# other multiplications
print(torch.ones(3, 4).mv(c))
print(torch.ones(3, 4) @ (c))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor(4.)
tensor(4.)
tensor(4.)
torch.Size([2, 3, 4, 6])
tensor([4., 4., 4.])
tensor([4., 4., 4.])


In [ ]:
# Tensor shape
a = torch.randn(2, 3, 4, 5)
print(a.shape)
print(a.size())     # equivalent
print(a.shape[2])
print(a.size(3))
print(a.size()[3])

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
4
5
5


In [ ]:
# Reduction operators
matrix = torch.tensor([[1.0, 2.0, 3.0],
                       [4.0, 5.0, 6.0]])
print(matrix.mean())
print(matrix.sum())
print(matrix.min())
print(matrix.max())

# Can also do reduction along a dim
print(matrix.mean(dim=1))   # Rows reduced
print(matrix.sum(dim=0))   # Columns reduced

a = torch.rand(2, 3, 4, 5)
print(a.sum(dim=2).shape)

tensor(3.5000)
tensor(21.)
tensor(1.)
tensor(6.)
tensor([2., 5.])
tensor([5., 7., 9.])
torch.Size([2, 3, 5])


In [ ]:
# dtype and device matter
float_tensor = torch.tensor([0.1, 1.0])
int_tensor = torch.tensor(range(3))
bool_tensor = int_tensor > 1.5    # You may have seen this in NumPy

print(bool_tensor)
print(float_tensor.dtype, int_tensor.dtype, bool_tensor.dtype)

cpu_tensor = torch.zeros(3, device='cpu')
gpu_tensor = torch.ones(3, device='cuda')
print(cpu_tensor, gpu_tensor)
try:
    try_this = cpu_tensor + gpu_tensor    # NO, PyTorch doesn't allow you to mess up tensors on different devices
except RuntimeError as e:
    print(e)

tensor([False, False,  True])
torch.float32 torch.int64 torch.bool
tensor([0., 0., 0.]) tensor([1., 1., 1.], device='cuda:0')
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


In [ ]:
# dtype and device conversion, 3 equivalent ways
gpu_to_cpu_1 = gpu_tensor.cpu()
gpu_to_cpu_2 = gpu_tensor.to(device='cpu')
gpu_to_cpu_3 = gpu_tensor.to(cpu_tensor.device)
print(cpu_tensor + gpu_to_cpu_1 + gpu_to_cpu_2 + gpu_to_cpu_3)

int_to_float_1 = int_tensor.float()
int_to_float_2 = int_tensor.to(dtype=torch.float32)         # numpy: astype
int_to_float_3 = int_tensor.to(int_to_float_1.dtype)        # the same function .to() can do multiple things
print(int_tensor.dtype, int_to_float_1.dtype, int_to_float_2.dtype, int_to_float_3.dtype)

tensor([3., 3., 3.])
torch.int64 torch.float32 torch.float32 torch.float32


In [ ]:
# In-place operations
a_tensor = torch.rand(3)
an_alias = a_tensor         # an_alias has the same data as a_tensor
print(a_tensor, an_alias)

a_tensor += 10              # '+=' modifies 'a_tensor' in-place
print(a_tensor, an_alias)
a_tensor.add_(10)
print(a_tensor, an_alias)

tensor([0.3056, 0.6302, 0.7723]) tensor([0.3056, 0.6302, 0.7723])
tensor([10.3056, 10.6302, 10.7723]) tensor([10.3056, 10.6302, 10.7723])
tensor([20.3056, 20.6302, 20.7723]) tensor([20.3056, 20.6302, 20.7723])


In [ ]:
# Try again, without in-place operations
a_tensor = a_tensor + 10    # Create a new tensor and then bind it to 'a_tensor'
print(a_tensor, an_alias)

tensor([30.3056, 30.6302, 30.7723]) tensor([20.3056, 20.6302, 20.7723])


In [ ]:
# Typical two versions of operations
a_tensor = torch.rand(3)
an_alias = a_tensor

print(a_tensor.sub(10), an_alias)
print(a_tensor.sub_(10), an_alias)  # Note the '_' after 'sub'. Functions ends with '_' are the inplace versions.

tensor([-9.1281, -9.1334, -9.1124]) tensor([0.8719, 0.8666, 0.8876])
tensor([-9.1281, -9.1334, -9.1124]) tensor([-9.1281, -9.1334, -9.1124])


In [ ]:
# Clone a tensor when necessary
a_tensor = torch.rand(3)
a_copy = a_tensor.clone()   # Another way: a_copy = a_tensor + 0
print(a_tensor, a_copy)
a_tensor += 10
print(a_tensor, a_copy)

tensor([0.4520, 0.8598, 0.4087]) tensor([0.4520, 0.8598, 0.4087])
tensor([10.4520, 10.8598, 10.4087]) tensor([0.4520, 0.8598, 0.4087])


In [ ]:
# Dimensions
tensor_12 = torch.FloatTensor(range(12))
print(tensor_12.shape, tensor_12)

torch.Size([12]) tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [ ]:
# Change tensor shape
tensor_3x4 = tensor_12.view(3, 4)
print(tensor_3x4.shape, tensor_3x4)

torch.Size([3, 4]) tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [ ]:
# But be careful about view()
tensor_12 += 1.0    # The two tensors share the same data(storage)!
print(tensor_3x4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
# A lazy way to change shape
tensor_1xIDKx2 = tensor_3x4.view(1, -1, 2)    # PyTorch will calculate a proper number for '-1', but don't put multiple '-1'
print(tensor_1xIDKx2.shape, tensor_1xIDKx2)

torch.Size([1, 6, 2]) tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])


In [ ]:
# Slicing
print(tensor_3x4[0])      # Take the first row
print(tensor_3x4[:, 1])   # Take the second column, ':' means collecting everything in that dim
print(tensor_3x4[2, 3])   # Take the bottom-right element

print(tensor_12[3:15:2])  # Fancier use of ':', start_idx : end_idx : step_size, range(start, end, step)

print(tensor_12[[5, 2, 1]])     # Use a list of indices

print(tensor_1xIDKx2[..., 1])   # '...' means multiple dims
print(tensor_1xIDKx2[:, :, 1])  # Identical

print(tensor_3x4[:, -1])

tensor([1., 2., 3., 4.])
tensor([ 2.,  6., 10.])
tensor(12.)
tensor([ 4.,  6.,  8., 10., 12.])
tensor([6., 3., 2.])
tensor([[ 2.,  4.,  6.,  8., 10., 12.]])
tensor([[ 2.,  4.,  6.,  8., 10., 12.]])
tensor([ 4.,  8., 12.])


In [3]:
# Element selection
a = -torch.arange(10)
print(a)

# Select by indices
print(a[[2, 3, 4, 7]])

# Select by mask
mask = a % 2 == 1
print(mask)
print(a[mask])

# Even select by indices/masks stored in another tensor
b = torch.tensor([[2, 3], [4, 1]]) # c = a[b], c[i][j] = a[b[i][j]]
print(a[b])

c = torch.randn(4, 5, 6)
b = c.max(dim=-1).values > 1
print(b.shape, c.shape, b.sum())            # mask's shape must be a prefix of a's shape
print(c[b].shape)                           # The first 2 dimensions will be "flattened"

tensor([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])
tensor([-2, -3, -4, -7])
tensor([False,  True, False,  True, False,  True, False,  True, False,  True])
tensor([-1, -3, -5, -7, -9])
tensor([[-2, -3],
        [-4, -1]])
torch.Size([4, 5]) torch.Size([4, 5, 6]) tensor(14)
torch.Size([14, 6])


In [ ]:
# Single-element tensor
single_element = tensor_3x4[2, 3]
print(single_element.shape, single_element)

another_single_element = single_element.view(1, 1, 1, 1)
print(another_single_element.shape, another_single_element)

# Use item() to access the actual value (no longer a tensor)
print(single_element.item(), another_single_element.item())

torch.Size([]) tensor(12.)
torch.Size([1, 1, 1, 1]) tensor([[[[12.]]]])
12.0 12.0


In [ ]:
# Pack tensors together
one_image = torch.rand(3, 160, 90)
another_image = torch.rand(3, 160, 90)

# stack() creates a new dim
batched_images = torch.stack([one_image, one_image, another_image, another_image],
                             dim=2)
print((batched_images[:, :, 0] - one_image).abs().max())
print((batched_images[:, :, 2] - another_image).abs().max())
print(batched_images.shape)

batched_images = torch.stack([one_image, one_image, another_image, another_image],
                             dim=-1)
print((batched_images[..., 0] - one_image).abs().max())
print((batched_images[..., 2] - another_image).abs().max())
print(batched_images.shape)

# cat() concatenates tensors in a given dim
another_image = torch.rand(3, 160, 100)
cated_images = torch.cat([one_image, one_image, another_image, another_image],
                         dim=-1)
print(cated_images.shape)
batched_images = torch.cat([one_image.unsqueeze(-1), one_image.unsqueeze(-1), one_image.unsqueeze(-1), one_image.unsqueeze(-1)],
                             dim=-1)
print(batched_images.shape)

tensor(0.)
tensor(0.)
torch.Size([3, 160, 4, 90])
tensor(0.)
tensor(0.)
torch.Size([3, 160, 90, 4])
torch.Size([3, 160, 380])
torch.Size([3, 160, 90, 4])


In [ ]:
# Broadcasting
x = torch.ones(2, 3)
y = torch.ones(2, 3) * 1.5
print(x + y)

# Adding 2x3 and 2x4 matrices causes dimension mismatch
try:
    z = torch.ones(2, 4) * 1.5
    print(x + z)
except RuntimeError as e:
    print(e)

# But 2x3 + 2x1 works!
w = torch.ones(2, 1) * 1.5
print(x + w)    # Same as x + y

tensor([[2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000]])
The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
tensor([[2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000]])


In [ ]:
# When the dimension sizes either are equal, or one of them is 1,
# we say the two tensors are broadcastable
x = torch.rand(2, 3, 1)
y = torch.rand(1, 3, 6)
print((x + y).shape)

x = torch.rand(2, 3, 1).expand(2, 3, 6)     # equivalent
y = torch.rand(1, 3, 6).expand(2, 3, 6)
print((x + y).shape)

# It's OK even when some dimensions are missing from the left
x = torch.rand(5, 1, 2, 3)
y = torch.rand(   6, 1, 1)
print((x + y).shape)

# This is exactly why "tensor times scalor" works
x = torch.rand([2, 3, 4, 5])
y = torch.rand([          ])    # scalor, or single element tensor
print((x * y).shape)

# Easier adjusting for broadcasting
x = torch.rand(2,    4,    6)
y = torch.rand(   3,    5   )
x1 = x[:,    None, :,    None, :   ]        # will make an extra dimension of size 1 at the "None" place
y1 = y[None, :,    None, :,    None]        # same as y1.unsqueeze(0).unsqueeze(2).unsqueeze(4)
print(x1.shape, y1.shape, (x1 * y1).shape)

torch.Size([2, 3, 6])
torch.Size([2, 3, 6])
torch.Size([5, 6, 2, 3])
torch.Size([2, 3, 4, 5])
torch.Size([2, 1, 4, 1, 6]) torch.Size([1, 3, 1, 5, 1]) torch.Size([2, 3, 4, 5, 6])


In [ ]:
# Efficiency
import time
a = torch.randn(10000, 200)

# With reduction operations
start = time.time()
S = a.sum()                         # Very Fast
print(S)
print(time.time() - start, "sec")

# With iterations
start = time.time()
S = 0
for i in range(10000):
    for j in range(200):
        S += a[i][j]                # Iterations and loops are much slower (at least 100x)!
print(S)
print(time.time() - start, "sec")

# Hybrid
start = time.time()
S = 0
for i in range(10000):
    S += a[i].sum()
print(S)
print(time.time() - start, "sec")

tensor(-180.7419)
0.0012886524200439453 sec
tensor(-180.7586)
9.742851257324219 sec
tensor(-180.7416)
0.06926631927490234 sec


In [ ]:
# Homework 1 Code, w/o loops
# Passes ALL the tests within 3 sec

def bayes_MAP(X, y):
    return torch.stack([
        X[y == 0].sum(dim=0) / (y == 0).sum(),      # X[y == 0]: masked select, (y == 0).sum(): reduction
        X[y == 1].sum(dim=0) / (y == 1).sum(),
    ], dim=0)

def bayes_MLE(y):
    return (y == 0).sum() / y.shape[0]

def bayes_classify(D, p, X):
    p0 = D[[0]] * X + (1 - D[[0]]) * (1 - X)        # Element-wise operations, without any loop
    p1 = D[[1]] * X + (1 - D[[1]]) * (1 - X)

    s0 = p.log() + p0.log().sum(dim=1)
    s1 = (1 - p).log() + p1.log().sum(dim=1)

    return (s1 >= s0).long()

def gaussian_MAP(X, y):
    return torch.stack([
        X[y == 0].mean(dim=0),
        X[y == 1].mean(dim=0),
    ], dim=0), torch.stack([
        X[y == 0].var(0, unbiased=False),
        X[y == 1].var(0, unbiased=False),
    ], dim=0)

def gaussian_MLE(y):
    return (y == 0).sum() / y.shape[0]

def gaussian_classify(mu, sigma2, p, X):
    log_pdf = lambda mu, sigma2, x : (-(x - mu).pow(2) / (2 * sigma2)) - 0.5 * (2 * torch.pi * sigma2).log()

    log_p0 = log_pdf(mu[[0]], sigma2[[0]], X)       # mu[[0]]: equivalent to mu[0].unsqueeze(0), for broadcasting in (x - mu)
    log_p1 = log_pdf(mu[[1]], sigma2[[1]], X)

    s0 = p.log() + log_p0.sum(dim=1)
    s1 = (1 - p).log() + log_p1.sum(dim=1)

    return (s1 >= s0).long()

## Autograd
The reason why we use PyTorch for machine learning.

(Also why is banned in Homework 2 Code)

In [ ]:
# Let's first define a function
def f(x):
    return (x ** 2).sum()

# We know f'(x) = 2x, but when f becomes more complicated
# we really don't want to calculate f'(x)

In [ ]:
# PyTorch can calculate gradients for us
x = torch.ones(4, requires_grad=True)   # PyTorch, please remember to get gradients of x for me
x = torch.ones(4).requires_grad_(True)
print(x)

y = f(x)
print(y)

y.backward()
print(x.grad)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor(4., grad_fn=<SumBackward0>)
tensor([2., 2., 2., 2.])


In [ ]:
# Remember, gradients will be 'accumulated'
y_again = f(x)
y_again.backward()    # What if I do backward again?
print(x.grad)

tensor([10., 10., 10., 10.])


In [ ]:
# So please clear gradients before back-prop
x.grad.zero_()
y_againagain = f(x)
y_againagain.backward()
print(x.grad)

x.grad = None
y_againagain = f(x)
y_againagain.backward()
print(x.grad)

tensor([2., 2., 2., 2.])
tensor([2., 2., 2., 2.])


In [ ]:
# PyTorch decides requires_grad smartly when creating new tensors
a_plsgrad = torch.ones(3, requires_grad=True)
b_nograd = torch.zeros(3)   # False by default
c = b_nograd + 1
d = a_plsgrad * c

# So the computation graph looks like
# b -> c -> d <- a

print(a_plsgrad.requires_grad, b_nograd.requires_grad, c.requires_grad, d.requires_grad)

True False False True


In [ ]:
# When necessary, detach a tensor from computation graph
detached_d = d.detach()    # Returns same tensor with requires_grad=False
print(detached_d.requires_grad)

detached_d += 0.5          # Be careful about in-place modification after detaching
print(d, detached_d)       # So it's common to see .detach().clone() together

data_d = d.data             # Returns same tensor with requires_grad=False
print(data_d.requires_grad)

False
tensor([3., 3., 3.], grad_fn=<MulBackward0>) tensor([3., 3., 3.])
False


In [ ]:
# Now let's use an example to show the advantage of autograd in PyTorch
# We will use 3 methods to optimize f(x) with gradient descent
# x will move from 1 to 0

learning_rate = 0.1
iterations = 10
x0 = torch.tensor(1.0)

# Method 1: We do not know autograd, and we use PyTorch just like NumPy
x = x0
for i in range(iterations):
    y = f(x)
    grad = 2 * x    # Calculate gradients manually, this step can be painful
                    # if your objective function is more complicated
    print(x, y, grad)
    x = x - learning_rate * grad  # GD update

tensor(1.) tensor(1.) tensor(2.)
tensor(0.8000) tensor(0.6400) tensor(1.6000)
tensor(0.6400) tensor(0.4096) tensor(1.2800)
tensor(0.5120) tensor(0.2621) tensor(1.0240)
tensor(0.4096) tensor(0.1678) tensor(0.8192)
tensor(0.3277) tensor(0.1074) tensor(0.6554)
tensor(0.2621) tensor(0.0687) tensor(0.5243)
tensor(0.2097) tensor(0.0440) tensor(0.4194)
tensor(0.1678) tensor(0.0281) tensor(0.3355)
tensor(0.1342) tensor(0.0180) tensor(0.2684)


In [ ]:
# Homework 2 Code in Method 1
# This is the required implementation
# I will not tell you here before the final deadline!

def linear_gd(X, Y, lrate=0.01, num_iter=1000):
    n = X.shape[0]
    X = torch.cat([torch.ones(n, 1), X], dim=1)
    w = torch.zeros(X.shape[1], 1)
    Y = Y.reshape([-1, 1])

    for t in range(num_iter):
        w = w - lrate * 2 / n * X.t() @ (X @ w - Y)

    return w

In [ ]:
# Method 2: Let PyTorch calculate gradients for us
x = x0.clone()
x.requires_grad = True    # Set the flag to inform PyTorch
for i in range(iterations):
    y = f(x)
    if x.grad:
        x.grad.zero_()        # Remember to clear before every backward()
    y.backward()              # Back-prop
    print(x, y, x.grad)
    with torch.no_grad():     # Set a context, where all operations will not record gradients
        x -= learning_rate * x.grad   # Why we use in-place '-='?

tensor(1., requires_grad=True) tensor(1., grad_fn=<SumBackward0>) tensor(2.)
tensor(0.8000, requires_grad=True) tensor(0.6400, grad_fn=<SumBackward0>) tensor(1.6000)
tensor(0.6400, requires_grad=True) tensor(0.4096, grad_fn=<SumBackward0>) tensor(1.2800)
tensor(0.5120, requires_grad=True) tensor(0.2621, grad_fn=<SumBackward0>) tensor(1.0240)
tensor(0.4096, requires_grad=True) tensor(0.1678, grad_fn=<SumBackward0>) tensor(0.8192)
tensor(0.3277, requires_grad=True) tensor(0.1074, grad_fn=<SumBackward0>) tensor(0.6554)
tensor(0.2621, requires_grad=True) tensor(0.0687, grad_fn=<SumBackward0>) tensor(0.5243)
tensor(0.2097, requires_grad=True) tensor(0.0440, grad_fn=<SumBackward0>) tensor(0.4194)
tensor(0.1678, requires_grad=True) tensor(0.0281, grad_fn=<SumBackward0>) tensor(0.3355)
tensor(0.1342, requires_grad=True) tensor(0.0180, grad_fn=<SumBackward0>) tensor(0.2684)


In [ ]:
# Homework 2 Code in Method 2
# Will get 0 points on GradeScope, since "backward()" function is removed
# But, you can use it for debugging

def linear_gd(X, Y, lrate=0.01, num_iter=1000):

    N = X.size(0)
    X = torch.cat([torch.ones(N, 1), X], dim=1)
    d = X.size(1)
    w = torch.zeros(d, 1).float().requires_grad_()

    for iter in range(num_iter):
        loss = 0 # You should implement it by yourself!
        w.grad = None               # GD HERE
        loss.backward()             # GD HERE
        with torch.no_grad():       # GD HERE
            w -= lrate * w.grad     # GD HERE

    return w.detach()

In [ ]:
# Method 3: Use PyTorch optimizers (Recommended!)
x = x0.clone()
x.requires_grad = True    # Set the flag to inform PyTorch
optimizer = torch.optim.SGD([x], lr=learning_rate)
for i in range(iterations):
    y = f(x)
    optimizer.zero_grad()   # Clear gradients
    y.backward()            # Back-prop
    print(x, y, x.grad)
    optimizer.step()        # Let optimizer update parameters using calculated gradients

tensor(1., requires_grad=True) tensor(1., grad_fn=<SumBackward0>) tensor(2.)
tensor(0.8000, requires_grad=True) tensor(0.6400, grad_fn=<SumBackward0>) tensor(1.6000)
tensor(0.6400, requires_grad=True) tensor(0.4096, grad_fn=<SumBackward0>) tensor(1.2800)
tensor(0.5120, requires_grad=True) tensor(0.2621, grad_fn=<SumBackward0>) tensor(1.0240)
tensor(0.4096, requires_grad=True) tensor(0.1678, grad_fn=<SumBackward0>) tensor(0.8192)
tensor(0.3277, requires_grad=True) tensor(0.1074, grad_fn=<SumBackward0>) tensor(0.6554)
tensor(0.2621, requires_grad=True) tensor(0.0687, grad_fn=<SumBackward0>) tensor(0.5243)
tensor(0.2097, requires_grad=True) tensor(0.0440, grad_fn=<SumBackward0>) tensor(0.4194)
tensor(0.1678, requires_grad=True) tensor(0.0281, grad_fn=<SumBackward0>) tensor(0.3355)
tensor(0.1342, requires_grad=True) tensor(0.0180, grad_fn=<SumBackward0>) tensor(0.2684)


In [ ]:
# Homework 2 Code in Method 3
# Will get 0 points on GradeScope too, since "torch.optim.SGD" class is removed
# Still, you can use it for debugging

def linear_gd(X, Y, lrate=0.01, num_iter=1000):
    from torch.optim import SGD

    N = X.size(0)
    X = torch.cat([torch.ones(N, 1), X], dim=1)
    d = X.size(1)
    w = torch.zeros(d, 1).float().requires_grad_()

    opt = SGD([w], lr=lrate)

    for iter in range(num_iter):
        loss = 0 # You should implement it by yourself!
        opt.zero_grad()     # GD HERE
        loss.backward()     # GD HERE
        opt.step()          # GD HERE

    return w.detach()

## Networks
`torch.nn` provides convenient interfaces to construct neural networks.

In [ ]:
# Common shortcuts
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# Basic building blocks in torch.nn

# Linear layer / Fully connected (FC) / Dense layer
linear = nn.Linear(4, 6, bias=True)
x = torch.rand(2, 4)
y = linear(x)   # Use it as if 'linear' is a function
print(y.shape)
print(y)

y = x @ linear.weight.T + linear.bias   # What actually happens in the forward pass
print(y.shape)
print(y)

torch.Size([2, 6])
tensor([[ 0.2701,  0.3206, -0.0573, -0.2140,  0.5556,  0.2814],
        [ 0.0327,  0.3245,  0.1390, -0.1539,  0.3063, -0.0343]],
       grad_fn=<AddmmBackward0>)
torch.Size([2, 6])
tensor([[ 0.2701,  0.3206, -0.0573, -0.2140,  0.5556,  0.2814],
        [ 0.0327,  0.3245,  0.1390, -0.1539,  0.3063, -0.0343]],
       grad_fn=<AddBackward0>)


In [ ]:
# nn.Module is the base class for all layers and networks in PyTorch
print(isinstance(linear, nn.Module))

# Parameters in nn.Module are nn.Parameter, a special sub-class of Tensor
print(isinstance(linear.weight, nn.Parameter))

# nn.Parameter has requires_grad=True, automatically
print(linear.weight.requires_grad)
a = nn.Parameter(torch.randn(2, 3))
print(a.requires_grad)

# We can list all the parameters in nn.Module
for name, param in linear.named_parameters():
    print(name, param.shape)
opt = torch.optim.SGD(linear.parameters(), lr=0.1)

True
True
True
True
weight torch.Size([6, 4])
bias torch.Size([6])


In [ ]:
# Batched computation
linear = nn.Linear(4, 100, bias=True)
larger_x = torch.rand(8, 7, 6, 5, 4)  # 8 x 7 x 6 x 5 vectors in 4d
larger_y = linear(larger_x)           # passing through this layer in a batch
print(larger_y.shape)                 # applied on the last dimension

torch.Size([8, 7, 6, 5, 100])


In [ ]:
# Convolutional layer
conv = nn.Conv2d(3, 16, kernel_size=3, padding=1)
x = torch.rand(3, 160, 90)          # Suppose this is a 160 x 90 RGB image
batched_x = x.view(1, 3, 160, 90)   # Unfortunately, 2D conv only takes 4D (B x N x H x W) tensor
y = conv(batched_x)
print(y.shape)

torch.Size([1, 16, 160, 90])


In [ ]:
# Activation and pooling
x = torch.rand(1, 1, 3, 3)
print(x)

relu = nn.ReLU()    # max(0, x)
y = relu(x)
print(y)

maxpool = nn.MaxPool2d(kernel_size=3)
z = maxpool(y)
print(z)

tensor([[[[0.5330, 0.6533, 0.1225],
          [0.0760, 0.9331, 0.4258],
          [0.8289, 0.9744, 0.9592]]]])
tensor([[[[0.5330, 0.6533, 0.1225],
          [0.0760, 0.9331, 0.4258],
          [0.8289, 0.9744, 0.9592]]]])
tensor([[[[0.9744]]]])


In [ ]:
# It's common to use nn.functional as an alternative
# when your layer is parameter-less
# such as activation layers, pooling layers, and loss function

x = torch.randn(3, 3)
print(x)

# Method 1: Define a layer and then apply
relu = nn.ReLU()
y = relu(x)
print(y)

# Method 2: Directly use a function
# We already have 'import torch.nn.functional as F'
y = F.relu(x)
print(y)

tensor([[-0.4878, -0.4088,  0.4850],
        [ 2.8901,  0.7068,  0.3607],
        [ 0.6796, -0.1972,  1.2925]])
tensor([[0.0000, 0.0000, 0.4850],
        [2.8901, 0.7068, 0.3607],
        [0.6796, 0.0000, 1.2925]])
tensor([[0.0000, 0.0000, 0.4850],
        [2.8901, 0.7068, 0.3607],
        [0.6796, 0.0000, 1.2925]])


In [ ]:
# Loss function
# MSE loss
loss_fn = nn.MSELoss(reduction='mean')  # Equivalent. This is a nn.Module.
target = torch.ones(1)
loss = loss_fn(z.view(1), target)
print(loss)
loss = F.mse_loss(z.view(1), target)
print(loss)

# Cross Entropy loss
# Compute cross entropy for classifications
# https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html
# The "pred" is logits (likelihood score), not probability
pred = torch.randn(100, 10)                         # 100 objects, 10 classes
target = torch.randint(low=0, high=9, size=[100])   # ground-truth labels
loss_fn = nn.CrossEntropyLoss()
print(loss_fn(pred, target))
print(F.cross_entropy(pred, target))
# with probability: NLLLoss


# Binary Cross Entropy loss
# Loss between two probabilities
# https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html?highlight=bce#torch.nn.BCELoss'
pred = torch.rand(100)      # probability
pred_logits = pred.logit()  # logits (likelihood), covert it back by pred_logits.sigmoid()
target = torch.rand(100)
print(F.binary_cross_entropy(pred, target))
print(F.binary_cross_entropy_with_logits(pred_logits, target))
print(nn.BCELoss()(pred, target))
print(nn.BCEWithLogitsLoss()(pred_logits, target))

tensor(0.0007)
tensor(0.0007)
tensor(2.8122)
tensor(2.8122)
tensor(1.1445)
tensor(1.1445)
tensor(1.1445)
tensor(1.1445)


In [ ]:
# Build a multi-layer network

# Method 1: Use nn.Sequential
# When your network has a very simple structure of a sequence of layers

# Say we want a multi-layer perceptron (MLP) with
# 8-d input, 1-d output,
# two hidden layers with width 32,
# and ReLU activations.
model_1 = nn.Sequential(
    nn.Linear(8, 32),
    nn.ReLU(),
    nn.Linear(32, 32),
    nn.ReLU(),
    nn.Linear(32, 32),
    nn.ReLU(),
    nn.Linear(32, 1)
)

x = torch.rand(10, 8)
y = model_1(x)
print(y.shape)

torch.Size([10, 1])


In [ ]:
# We can list the sub-modules in a network
for name, module in model_1.named_children():
    print(name, module)

0 Linear(in_features=8, out_features=32, bias=True)
1 ReLU()
2 Linear(in_features=32, out_features=32, bias=True)
3 ReLU()
4 Linear(in_features=32, out_features=32, bias=True)
5 ReLU()
6 Linear(in_features=32, out_features=1, bias=True)


In [ ]:
# named_modules() will iterate over the network itself, the networks' children,
# the networks' children's children...
for name, module in model_1.named_modules():
    print(name, module)

 Sequential(
  (0): Linear(in_features=8, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=1, bias=True)
)
0 Linear(in_features=8, out_features=32, bias=True)
1 ReLU()
2 Linear(in_features=32, out_features=32, bias=True)
3 ReLU()
4 Linear(in_features=32, out_features=32, bias=True)
5 ReLU()
6 Linear(in_features=32, out_features=1, bias=True)


In [ ]:
print(model_1)

Sequential(
  (0): Linear(in_features=8, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=1, bias=True)
)


In [ ]:
# Method 2: Define our own network class

class OurMLP(nn.Module):      # Must be a sub-class of nn.Module
                              # At least write your own __init__() and forward()

    def __init__(self, in_dim, hidden_dim, out_dim):
        super().__init__()    # Calls nn.Module's __init__() to do some preparation
                              # Equivalent to super(OurMLP, self).__init__()
        self.linear1 = nn.Linear(in_dim, hidden_dim)
        self.linear2 = nn.Linear(hidden_dim, hidden_dim)
        self.linear3 = nn.Linear(hidden_dim, hidden_dim)
        self.linear4 = nn.Linear(hidden_dim, out_dim)
        self.relu = nn.ReLU() # Can be reused

    def forward(self, x):     # Define the forward pass
                              # You don't need to write backward() yourself
        y = self.relu(self.linear1(x))
        y = self.relu(self.linear2(y))
        y = self.relu(self.linear3(y))
        y = self.linear4(y)
        return y

model_2 = OurMLP(8, 32, 1)   # After defining the class, we need to instantiate it

x = torch.rand(10, 8)
y = model_2(x)
print(y.shape)

torch.Size([10, 1])


In [ ]:
print(model_2)

OurMLP(
  (linear1): Linear(in_features=8, out_features=32, bias=True)
  (linear2): Linear(in_features=32, out_features=32, bias=True)
  (linear3): Linear(in_features=32, out_features=32, bias=True)
  (linear4): Linear(in_features=32, out_features=1, bias=True)
  (relu): ReLU()
)


In [ ]:
# Put everything together
import random

# Generate some random data to fit
X = torch.randn(1000, 8)
Y = (X ** 2 + 1.5 * X - 3).mean(dim=1)

# Create our model
model = OurMLP(8, 32, 1)

# Set the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# Start our training
for i in range(20):
    # Randomly sample a batch
    sample_indices = random.choices(range(1000), k=100)
    X_sample = X[sample_indices]
    Y_sample = Y[sample_indices]

    # Calculate our prediction
    Y_hat = model(X_sample)

    # Get the loss
    loss = F.mse_loss(Y_hat.view(-1), Y_sample)
    print(i, loss.item())

    # Gradient step
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 3.905557155609131
1 2.2145509719848633
2 0.9848006367683411
3 0.8547276258468628
4 0.6065813899040222
5 0.34173429012298584
6 0.5407477617263794
7 0.7001140713691711
8 0.6500923037528992
9 0.6037231683731079
10 0.5115855932235718
11 0.49468985199928284
12 0.5415174961090088
13 0.5753231644630432
14 0.5858321189880371
15 0.5660331845283508
16 0.3456287384033203
17 0.5253176093101501
18 0.35942187905311584
19 0.30562347173690796


In [ ]:
# Dataset and dataloader
# These are typical structures we use to organize our data in PyTorch
# Read https://pytorch.org/tutorials/beginner/basics/data_tutorial.html
# for further information

# First let's clarify a few concepts
# For a larger dataset, we cannot feed the whole dataset into the model at once
# so we use stochastic gradient descent
# In each *iteration*, we sample a *batch* of data from the dataset
# Calculate gradient on the batch, and do updates
# One *epoch* consists of multiple such iterations
# which means that the entire dataset has been passed for once
# So, number of total iterations = (number of epochs) * (dataset size / batch size)

# We can re-write example above with dataset and dataloader as an example

# Create dataset
dataset = torch.utils.data.TensorDataset(X, Y)

# Create dataloader, with batch size 100 and random sampling
dataloader = torch.utils.data.DataLoader(dataset, batch_size=100, shuffle=True)

# Create our model
model = OurMLP(8, 32, 1)

# Set the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# Start our training for 2 epochs, 20 iterations in total
for epoch in range(2):
    # Randomly sample a batch
    # If you don't need iteration number, simply write
    # for X_sample, Y_sample in dataloader: ...
    for iteration, (X_sample, Y_sample) in enumerate(dataloader):

        # Calculate our prediction
        Y_hat = model(X_sample)

        # Get the loss
        loss = F.mse_loss(Y_hat.view(-1), Y_sample)
        print('Epoch', epoch, 'Iteration', iteration, loss.item())

        # Gradient step
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

Epoch 0 Iteration 0 4.652416229248047
Epoch 0 Iteration 1 1.9855537414550781
Epoch 0 Iteration 2 0.7771167159080505
Epoch 0 Iteration 3 0.7669622898101807
Epoch 0 Iteration 4 0.7844502329826355
Epoch 0 Iteration 5 0.46512648463249207
Epoch 0 Iteration 6 0.7180795073509216
Epoch 0 Iteration 7 0.48922836780548096
Epoch 0 Iteration 8 0.7356159687042236
Epoch 0 Iteration 9 0.6651875376701355
Epoch 1 Iteration 0 0.4705624282360077
Epoch 1 Iteration 1 0.6281638145446777
Epoch 1 Iteration 2 0.4959659278392792
Epoch 1 Iteration 3 0.37225982546806335
Epoch 1 Iteration 4 0.45131441950798035
Epoch 1 Iteration 5 0.5445260405540466
Epoch 1 Iteration 6 0.29286232590675354
Epoch 1 Iteration 7 0.39144429564476013
Epoch 1 Iteration 8 0.3864902853965759
Epoch 1 Iteration 9 0.34683871269226074


## Misc & Advanced

`view()` vs. `reshape()`

`torch.tensor` vs. `torch.Tensor`

Gradient of `relu()`

`max()` vs. `amax()`

`gather` and `scatter`

Sparse tensor

In [ ]:
# view() vs reshape()
tensor_12 = torch.FloatTensor(range(12))

# view() always shares the same data storage
tensor_3x4 = tensor_12.view(3, 4)
tensor_12 += 1.0
print(tensor_12, tensor_3x4)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
# But sometimes PyTorch does not allow a different view()
# because the tensor is not 'contiguous'
tensor_4x3 = tensor_3x4.T
try:
    tensor_6x2 = tensor_4x3.view(6, 2)
except RuntimeError as e:
    print(e)

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [ ]:
# One solution is to use contiguous() before view()
tensor_6x2 = tensor_4x3.contiguous().view(6, 2)
print(tensor_6x2)

tensor([[ 1.,  5.],
        [ 9.,  2.],
        [ 6., 10.],
        [ 3.,  7.],
        [11.,  4.],
        [ 8., 12.]])


In [ ]:
# Another is to use reshape(), which does not always guarantee same data storage
tensor_6x2 = tensor_3x4.T.reshape(6, 2)
print(tensor_6x2)

tensor_3x4 += 1.0
print(tensor_3x4, tensor_6x2)

tensor([[ 1.,  5.],
        [ 9.,  2.],
        [ 6., 10.],
        [ 3.,  7.],
        [11.,  4.],
        [ 8., 12.]])
tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.]]) tensor([[ 1.,  5.],
        [ 9.,  2.],
        [ 6., 10.],
        [ 3.,  7.],
        [11.,  4.],
        [ 8., 12.]])


In [ ]:
# torch.tensor() vs torch.Tensor()

# Coding convention in Python:
# this_is_a_function and ThisIsAClass
# so torch.tensor() is a function that creates a tensor
# and torch.Tensor() is a class
# (actually calling its __init__() construction function)

# torch.tensor() will decide dtype according to the input
print(torch.tensor([1, 2, 3]).dtype)
print(torch.tensor([1.0, 2, 3]).dtype)
print(torch.tensor([True, False]).dtype)

torch.int64
torch.float32
torch.bool


In [ ]:
# torch.Tensor is actually torch.FloatTensor by default
# So its always float dtype by calling torch.Tensor()
print(torch.Tensor([1, 2, 3]).dtype)
print(torch.Tensor([1.0, 2, 3]).dtype)
print(torch.Tensor([True, False]).dtype)

# In fact, there are other types of tensors other than Tensor
print(torch.LongTensor([1.5, 2.3]).dtype)
print(torch.DoubleTensor([1, 2, 3]).dtype)
print(torch.BoolTensor([1, 2, 3]).dtype)

torch.float32
torch.float32
torch.float32
torch.int64
torch.float64
torch.bool


In [ ]:
# PyTorch does have numerical problems

# Example: ReLU(x) = max(0, x)
# Its derivative is *undefined* at x=0, but PyTorch has to pick a value

x = torch.tensor(0.0, requires_grad=True)
y = F.relu(x)
y.backward()
print(x.grad)

tensor(0.)


In [ ]:
# This may cause a problem

# Check this fact:
# For all x in R, x = ReLU(x) - ReLU(-x)
g = lambda x: F.relu(x) - F.relu(-x)
x = torch.tensor(3.14, requires_grad=True)
y = g(x)
print(y)

tensor(3.1400, grad_fn=<SubBackward0>)


In [ ]:
# So if we take the derivative of g(x) = ReLU(x) - ReLU(-x)
# it should always be 1, even at x=0
# but PyTorch does *not* think so
y.backward()
print(x.grad)

x = torch.tensor(0.0, requires_grad=True)
y = g(x)
y.backward()
print(x.grad)

# Don't feel too worried about that, in practice we don't have this kind of problem

tensor(1.)
tensor(0.)


In [ ]:
# max() vs amax()

# max() returns the maximum value in a tensor
matrix = torch.rand(3, 3)
print(matrix)
print(matrix.max())

tensor([[0.8339, 0.1383, 0.5487],
        [0.2701, 0.1914, 0.6071],
        [0.6095, 0.0441, 0.1375]])
tensor(0.8339)


In [ ]:
# But when you specify dim=x, max() returns something weird: pair of (values, indices)
print(matrix.max(dim=0))

torch.return_types.max(
values=tensor([0.8339, 0.1914, 0.6071]),
indices=tensor([0, 1, 1]))


In [ ]:
# What max() returns is actually a tuple
# The first one in the tuple is the maximum values in each row
# The second is the 'argmax', the indices which point to the maximum values

# Sometimes this is annoying, if I need argmax() why not just call another function?
print(matrix.argmax(dim=0))
# amax() can be helpful if you do not need those indices
# amax() always only return the values
print(matrix.amax(dim=0))

tensor([0, 1, 1])
tensor([0.8339, 0.1914, 0.6071])


In [ ]:
# Advanced: gather
# out = input.gather(dim, index)
# out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
# out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
# out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2

# Sample usage: find topk for each row
a = torch.randn(5, 100)
c = torch.randn(5, 100)
indices = a.topk(10, largest=True, dim=-1).indices  # Each row contains the topk indices
b = c.gather(1, indices)                            # b[i][j] = c[i][indices[j]]
print(b.shape)

torch.Size([5, 10])


In [ ]:
# Advanced: scatter
# out.scatter_/scatter_reduce_(dim, index, src)
# self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0
# self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1
# self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2

# Sample usage 1: sum of each class
c = torch.randint(low=0, high=10, size=[100])    # 100 objects in 10 classes
v = torch.rand(100)                              # each value
s1 = torch.zeros(10).scatter(dim=0, index=c, src=v)
print(s1.shape)
# or equivalently, without scatter
s2 = torch.zeros(10)
s2[c] += v
print(s2.shape)
print((s1 - s2).abs().max())

# Sample usage 2: max of each class
m = torch.zeros(10).scatter_reduce(0, c, v, reduce='amax')
print(m)
# doesn't have a very simple equivalent way

torch.Size([10])
torch.Size([10])
tensor(0.)
tensor([0.9808, 0.9706, 0.9972, 0.9061, 0.7095, 0.9311, 0.9940, 0.9099, 0.9530,
        0.9643])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: UserWarning: scatter_reduce() is in beta and the API may change at any time. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1550.)


In [ ]:
# Advanced: sparse tensor (sparse coo tensor)
a = torch.randint(low=1, high=5, size=[5,6]) * (torch.randn(5, 6) > 0)
print(a)
print(a.to_sparse())

# You can construct a sparse tensor with indices, values and size
indices = torch.tensor([
    [0, 0],
    [0, 2],
    [0, 3],
    [1, 2],
    [1, 4],
    [1, 5],
    [2, 1],
    [2, 4],
    [2, 5],
    [3, 1],
    [4, 1],
    [4, 2]]).T
values = torch.tensor([3, 1, 4, 3, 4, 2, 4, 3, 4, 2, 1, 4])
b = torch.sparse_coo_tensor(indices=indices, values=values, size=(5, 6))
print(b.to_dense())

tensor([[1, 0, 3, 2, 0, 0],
        [0, 0, 2, 1, 0, 0],
        [4, 2, 0, 4, 0, 3],
        [0, 2, 1, 2, 0, 1],
        [0, 1, 3, 4, 4, 0]])
tensor(indices=tensor([[0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
                       [0, 2, 3, 2, 3, 0, 1, 3, 5, 1, 2, 3, 5, 1, 2, 3, 4]]),
       values=tensor([1, 3, 2, 2, 1, 4, 2, 4, 3, 2, 1, 2, 1, 1, 3, 4, 4]),
       size=(5, 6), nnz=17, layout=torch.sparse_coo)
tensor([[3, 0, 1, 4, 0, 0],
        [0, 0, 3, 0, 4, 2],
        [0, 4, 0, 0, 3, 4],
        [0, 2, 0, 0, 0, 0],
        [0, 1, 4, 0, 0, 0]])


In [ ]:
# Usage 1: If you only care about some positions in a matrix, you can use sparse tensor to get them
points = torch.randn(10000, 3)    # 100 points
important = torch.rand(10000, 10000) < 0.001
print(important.sum())
# I want to calculate all dist(points[i], point[j]) for important[i][j] is True
import time
# classical implementation
start = time.time()
pairwise_dist = (points[:, None, :] - points[None, :, :]).norm(dim=-1)
important_dist_1 = pairwise_dist[important]
print(time.time() - start, "sec")
# with sparse tensor
start = time.time()
important_indices = important.to_sparse().indices()
important_dist_2 = (points[important_indices[0]] - points[important_indices[1]]).norm(dim=-1)
print(time.time() - start, "sec")
print((important_dist_1 - important_dist_2).abs().max())

tensor(99891)
2.06976318359375 sec
0.23438739776611328 sec
tensor(0.)


In [ ]:
# Usage 2: If you want to multiply a matrix with a sparse matrix (e.g., adjacent matrix of a graph) for multiple times
M = torch.randn(5000, 5000) * (torch.rand(5000, 5000) < 0.001)
print((M != 0).sum())

# classical implementation
start = time.time()
V1 = torch.ones(5000, 1000)
for i in range(10):
    V1 = M @ V1
print(time.time() - start, "sec")
# with sparse tensor
start = time.time()
V2 = torch.ones(5000, 1000)
M_sparse = M.to_sparse()
for i in range(10):
    V2 = M_sparse @ V2
print(time.time() - start, "sec")
print((V1 - V2).abs().max())


tensor(25129)
4.181354284286499 sec
0.24363493919372559 sec
tensor(0.0034)
